language: python
dist: xenial

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.7
      env: CHECK_DOCS=1
    - python: 3.7
      env: CHECK_FORMATTING=1
    # The pypy tests are slow, so list them early
    - python: pypy3.5
    # Uncomment if you want to test on pypy nightly:
    # - language: generic
    #   env: USE_PYPY_NIGHTLY=1
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev

script:
  - ci/travis.sh
